name: HoYoLAB Auto Check-In

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Create config.json5
        run: |
          cat > config.json5 <<EOF
          {
            accounts: [
              {
                cookies: {
                  ltuid_v2: "${{ secrets.LTUID_V2 }}",
                  ltoken_v2: "${{ secrets.LTOKEN_V2 }}",
                  account_mid_v2: "${{ secrets.ACCOUNT_MID_V2 }}"
                },

                games: [
                  "genshin",
                  "starrail",
                  "zzz"
                ]
              }
            ]
          }
          EOF

      - name: Run HoYoLAB check-in
        run: node index.js
