name: HoYoLAB Auto Check-In

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v5
        with:
          node-version: 22

      - run: npm install

      - name: Create config.json5
        run: |
          cat > config.json5 <<EOF
          {
            accounts: [
              {
                cookies: {
                  ltuid_v2: "${{ secrets.LTUID_V2 }}",
                  ltoken_v2: "${{ secrets.LTOKEN_V2 }}",
                  account_mid_v2: "${{ secrets.ACCOUNT_MID_V2 }}"
                },

                games: [
                  "genshin",
                  "starrail",
                  "zzz"
                ]
              }
            ]
          }
          EOF

      - run: node index.js
