name: HoYoLAB Auto Check-In

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v5
        with:
          node-version: 22

      - run: npm install

      - name: Create env
        run: |
          echo "LTUID_V2=${{ secrets.LTUID_V2 }}" >> .env
          echo "LTOKEN_V2=${{ secrets.LTOKEN_V2 }}" >> .env
          echo "ACCOUNT_MID_V2=${{ secrets.ACCOUNT_MID_V2 }}" >> .env

      - run: npm start
